accounts/urls.py
from django.urls import path
from .views import ActivationView, LoginView, RegisterView, ActivateMssgView, UserUpdateView, UserProfileView
app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/', ActivateMssgView.as_view(), name='activate-mssg'),
    path('accounts/activate/<uidb64>/<token>/', ActivationView.as_view(), name='activate'),
    path('profile/edit/me/', UserUpdateView.as_view(), name='edit-profile'),
    path('profile/<slug:username>/', UserProfileView.as_view(), name='profile'),
]

blogging/urls.py
"""IT CONFIGURE ALL APPS URLS"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     
handler403 = 'blogging.views.custom_error_403'

main/urls.py
from django.urls import path, re_path
from . import views
from .views import AddPostView, IndexView, PostDetailView, EditPostView, DeletePostView, AllPostByUserView, SearchPostView, CategoryView
from django.contrib.auth.decorators import login_required

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category/<slug:cats>/', CategoryView, name='category'),
    path('search/', SearchPostView.as_view(), name='search'),
    path('add-post/', login_required(AddPostView.as_view()), name='add-post'),
    path('my/posts/', login_required(AllPostByUserView.as_view()), name='your-post'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('edit/post/<slug:slug>/', login_required(EditPostView.as_view()), name='edit-post'),
    path('delete/post/<slug:slug>/', login_required(DeletePostView.as_view()), name='delete-post'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from datetime import datetime, date
from tinymce.models import HTMLField

from django.conf import settings
User = settings.AUTH_USER_MODEL

STATUS_CHOICES = [
    ('d', 'draft'),
    ('p', 'published'),
    ('t', 'takendown')
]

class Category(models.Model):
    """Making category for blogs"""
    cate = models.CharField("Post's Category", max_length=125, unique=True)

    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.cate
    
    def save(self, *args, **kwargs):
        self.cate = self.cate.lower()
        return super(Category, self).save(*args, **kwargs)
    
    
class Post(models.Model):
    """Storing the blog title with date published"""
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    snippets = models.CharField(max_length=200)
    body= HTMLField()
    slug = models.SlugField(max_length=80, unique=True, null=False, help_text="This field take uer input")
    image= models.ImageField('Image', upload_to='images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, max_length=125, related_name='posts')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    featured = models.BooleanField(null=True)
    
    def __str__(self):
        """Format to show in admin panel"""
        return self.title + ' | Author: ' + str(self.author)
    
    def get_absolute_url(self):
        """Redirects me to the post-detail page after i created a post."""
        return reverse('main:post-detail', args=[str(self.slug)])
    

main/forms.py
from django import forms
from .models import Post
from tinymce.widgets import TinyMCE
    
class PostForm(forms.ModelForm):
    image = forms.ImageField(required=True)
    status = forms.CharField()
    class Meta:
        model = Post
        fields = (
            'title', 'category', 'body', 'snippets', 'slug', 'image', 'status')
        error_messages = {
            'slug': {
                'unique': "This url already exists!",
            }
        }
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control ftitle ttest', 'placeholder':'Enter your title here'}),
            'body': TinyMCE(attrs={'class':'tbody', 'placeholder':'Start Writing Your Post Here...'}),
            'snippets': forms.Textarea(attrs={'class':'form-control tsnippet'}),
            'category': forms.Select(attrs={'class':'form-control form-select text-capitalize', 'placeholder':'Select Category'}),
            'slug': forms.TextInput(attrs={'class':'form-control'}),
            'image': forms.FileInput(attrs={'class':'form-control m-image-f'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'snippets', 'body', 'slug', 'image', 'status')
        error_messages = {
            'slug': {
                'unique': "This url already exists!",
            }
        }
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control ftitle', 'placeholder':'Enter your title here'}),
            'snippets': forms.Textarea(attrs={'class':'form-control tsnippet'}),
            'category': forms.Select(attrs={'class':'form-control form-select text-capitalize', 'selected':'here'}),
            'body': TinyMCE(attrs={'class':'tbody', 'placeholder':'Start Writing Your Post Here...'}),
            'slug': forms.TextInput(attrs={'class':'form-control'}),
            'image': forms.FileInput(attrs={'class':'form-control'}),
        }
        
        

main/views.py
from unicodedata import category
from django.shortcuts import render
from django.views import generic
from pkg_resources import require
from .models import Category, Post
from .forms import PostForm, EditForm
from django.urls import reverse_lazy
from accounts.models import CustomUser
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.db.models import Q
from django.conf import settings
User = settings.AUTH_USER_MODEL

class IndexView(generic.ListView):
    """Shows the list view of all the blogs."""
    model = Post
    template_name = 'main/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_list'] = Post.objects.filter(status='p').order_by('-pub_date')
        context['featured_post'] = Post.objects.filter(status='p', featured=True).order_by('-pub_date')
        return context
    
class PostDetailView(generic.DetailView):
    """Shows the individual blog in detail."""
    model = Post
    template_name= 'main/post.html'

class AddPostView(generic.CreateView):
    """Add a new post view for our blog""" 
    model = Post
    form_class = PostForm
    template_name = 'main/add_post.html'
    
    def form_valid(self, PostForm):
        """Auto inserts the current logged user into the author field."""
        PostForm.instance.author = self.request.user
        return super().form_valid(PostForm)
 
class EditPostView(generic.UpdateView):
    """Update or edit the post by the author."""
    model = Post
    form_class = EditForm
    template_name = 'main/edit_post.html'
    success_url= "/{slug}"
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        post = self.get_object()
        if post.author != self.request.user:
            raise PermissionDenied
        
        return super(EditPostView, self).dispatch(request, *args, **kwargs)
  
class DeletePostView(generic.DeleteView):
    """Delete a post from the databsae."""
    model = Post
    template_name = 'main/delete_post.html'
    success_url= reverse_lazy('main:your-post')
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        post = self.get_object()
        if post.author != self.request.user:
            raise PermissionDenied
        
        return super(DeletePostView, self).dispatch(request, *args, **kwargs)

class AllPostByUserView(generic.ListView):
    model = Post
    template_name = 'main/your_post.html'
    
    def get_queryset(self):
        """arrange the post list in date by order, from new to old"""
        return Post.objects.filter(author=self.request.user).order_by('-pub_date')
    
    
class SearchPostView(generic.ListView):
    model = Post
    template_name="main/search.html"
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        if not query:
            raise Http404
        object_list = Post.objects.filter(Q(title__icontains=query) | Q(snippets__icontains=query), status='p')
        return object_list
    
def CategoryView(request, cats):
    try:
        category = Category.objects.get(cate=cats)
    except Category.DoesNotExist:
        raise Http404("Category does not exist")
    category_post = category.posts.all()
    return render(request, 'main/category.html', {'cats': cats, 'category_post':category_post})

main/templates/main/add_post.html
{% extends 'main/base.html' %}

{% block title%}
Create a New Post | Social Blogging
{% endblock %}

{% block start %}
<div class="container">
    <h1>Add New Post</h1>
    <div class="form-group">
        <form class="post-sec" autocomplete="off" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="left-sec">
                <p>
                    {{ form.title}}
                </p>
                <p>
                    {{form.body}}
            </div>
            <div class="right-sec">
                <div class="sec1">
                    <p>
                        <label for="id_tag">Select Categories:</label>
                        {{ form.category }}
                    </p>
                    {% comment %}
                    <p>
                        <label for="id_tag">Select Status:</label>
                        {{ form.status }}
                    </p>
                    {% endcomment %}
                    <p>
                        <label for="id_slug">Post Url</label>
                        {{ form.slug }}
                        {% if form.errors.slug %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{error}}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                    </p>
                </div>
                <div class="sec2">
                    <p>
                        <label for="id_tag">snippet <small>(Under 200 Characters)</small> </label>
                        {{ form.snippets }}
                    </p>
                </div>
                <!-- Display the image preview on the add image! -->
                <div class="sec3">
                    <input type="file" id="id_image" name="image" multiple accept="image/*" style="display:none" class="form-control">
                    <a href="#" id="fileSelect">Upload Image</a>
                    <div id="fileList">
                        <p>No image selected!</p>
                        <spam>
                        {% if form.errors.image %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{error}}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                        </spam>
                    </div>
                </div>
                <button class="btn btn-primary but1" name="status" id="id_status" type="submit" value="d">Save as Draft</button>
                <button class="btn btn-success" name="status" id="id_status" type="submit" value="p">Publish</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- My CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/layout.css' %}">
    {% block css %}{% endblock %}

    <!-- Fonts & icons -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.tiny.cloud/1/99he4v7dkvpeljvf5qfa7db89l6p6dbtz5dtsd4qoybi6wkl/tinymce/6/tinymce.min.js"
        referrerpolicy="origin"></script>
    
    <!-- Javascripts    -->
    <script type="text/javascript" src="{% static 'main/js/config.js' %}" defer></script>

    {% block head %}{% endblock %}
    <title>
        {% block title %}
        Social Blogging- A Blog made for You
        {% endblock %}
    </title>
</head>

<body>
    <div id="myOverlay" class="overlay">
        <span class="closebtn" onclick="closeSearch()" title="Close Overlay">x</span>
        <div class="overlay-content">
            <form action="{% url 'main:search' %}" method="get" autocomplete="off" class="form-search">
                <button type="submit"><i class="fa-solid fa-search"></i></button>
                <input type="text" id="mySearch" placeholder="Search Post..." name="q">
            </form>
        </div>
    </div>
    <div class="nav_primary">
        <div class="left_sec">
           <a class="logo" href="{% url 'main:index' %}">Social Blogging</a>
        </div>
        <div class="menu">
            <a class="underline" href="{% url 'main:index' %}">home</a>
            <a class="underline" href="{% url 'main:category' 'gaming' %}">Gaming</a>
            <a class="underline" href="{% url 'main:category' 'movies' %}">Movies</a>
            <a class="underline" href="{% url 'main:category' 'pc' %}">PC</a>
            <a class="underline" href="{% url 'main:category' 'tech' %}">Tech</a>
            <a class="underline" href="{% url 'main:category' 'coding' %}">Coding</a>
        </div>
        {% if user.is_authenticated %} 
        <div class="dropdown">
            <button class="search" onclick="openSearch()"><i class="fa-solid fa-magnifying-glass fa-lg sicon"></i></button>
            <a href="{% url 'main:add-post' %}" class="write"><i class="fa-solid fa-plus pi"></i>Write</a>
            <button type="" class="dropbtn" onclick="myFunction()">
                {% if user.user_image %}
                <img src="{{ user.user_image.url }}"
                    class="user_img circle pe">
                {% else %}
                <img src="{% static 'images\default.png' %}"
                    class="user_img circle pe">
                {% endif %}
                <i class="fa-solid fa-caret-down pe"></i>
            </button>   
            <div class="dropdown-content" id="myDropdown">
                <p class="uline">Logged in as<br><span>{{ user.username }}</span></p>
                <a href="{% url 'accounts:profile' user %}">Your profile</a>
                <a href="{% url 'accounts:edit-profile' %}">Edit Profile</a>
                <a href="{% url 'main:your-post' %}">Your posts</a>
                <a href="{% url 'logout' %}">Sign out</a>
            </div>
        </div>
        {% else %}
        <div class="right_sec">
            <button class="search" onclick="openSearch()"><i class="fa-solid fa-magnifying-glass fa-lg sicon"></i></button>
            <a class="mbut lbut" href="{% url 'accounts:login'%}">Login</a>
            <a class="mbut rbut" href="{% url 'accounts:register' %}">Sign up</a>
        </div>
        {% endif %}
    </div>

    {% block start %}
    {% endblock %}
    <!-- main body ends -->

    <!-- footer starts -->
    {% comment %} Using external footer.html file for easy of use. Call it with include.{% endcomment %}
    {% block footer %}
    <!-- {% include 'main/footer.html' %} -->
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/category.html
{% extends 'main/base.html' %}
{% block start %}
<div class="container">
    <h1>{{cats}} Categories</h1>
    <ul>
    {% for post in category_post %}
    <li><a id="post_link" href="{% url 'main:post-detail' post.pk %}">{{ post.title }}</a>
        <p>By {{ post.author.first_name }} {{ post.author.last_name }} | Published - {{ post.pub_date|date }}</p>
        <p>{{ post.snippets}}</p><p>{{post.category}}</p>
    </li><br />
    {% endfor %}
    </ul>
</div>
{% endblock %}

main/templates/main/delete_post.html
{% extends 'main/base.html' %}
{% block title%}Confirm Delete Post{% endblock %}
{% block start %}

    {% if user.id == post.author.id %}
    <div class="container">
        <h2>Delete: {{ post.title }}</h2>
    
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                <strong>Are you sure want to delete this post?</strong><br><br>
                <button class="btn btn-danger">Confirm Delete</button>
            </form>
        </div>
    </div>
    {% else %}
    <strong>PAGE NOT FOUND!!!</strong>
    {% endif %}

{% endblock %}

main/templates/main/edit_post.html
{% extends 'main/base.html' %}

{% block title%}
Edit post | Social Blogging
{% endblock %}

{% block start %}

<div class="container">
    <h1>Edit your Post:</h1>
    <div class="form-group">
        <form class="post-sec" autocomplete="off" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="left-sec">
                <p>
                    {{ form.title}}
                </p>
                <p>
                    {{form.body}}
                </p>
            </div>
            <div class="right-sec">
                <div class="sec1">
                    <p>
                        <label for="id_tag">Select Categories:</label>
                        {{ form.category }}
                    </p>
                    <p>
                        <label for="id_slug">Post Url</label>
                        {{ form.slug }}
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>Post with this URL already exists.</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% endif %}
                    </p>
                </div>
                <div class="sec2">
                    <p>
                        <label for="id_tag">snippet <small>(Under 200 Characters)</small> </label>
                        {{ form.snippets }}
                    </p>
                </div>
                <div class="sec3">
                    <p>
                        {{ form.image }}
                    </p>
                    {% if post.image %}
                    <img src="{{ post.image.url}}" alt="connect" style="max-width:100%; max-height: auto;">
                    {% endif %}
                </div>
                <button class="btn btn-primary but1" name="status" id="id_status" type="submit" value="d">Save as Draft</button>
                <button class="btn btn-success" name="status" id="id_status" type="submit" value="p">Publish Changes</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}

{% block start %}
<div class="content">
    <div class="p-card">
        {% if post_list %}
        <a href='{% url "main:post-detail"  post_list.0.slug %}' class="p-link">
        <img src="{{post_list.0.image.url}}" alt="" class="p-card-img">
        <div class="card-meta">
            <h2>{{ post_list.0.title}}</h2>
            <p>{{post_list.0.snippets}}</p>
        </div>
        </a>
        {% endif %}
    </div>
    <div class="t-sec">
        <div class="t-wrapper">
            <h2>Latest Trending</h2>
            <div class="trending-card">
                {% for post in featured_post %}
                <div class="trending">
                    <img src="{{ post.image.url }}" alt="" class="trending-img">
                    <div class="trending-info">
                        <p>{{post.category}}</p>
                        <h3>{{post.title}}</h3>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% comment %}
        Calling post_list from the index view context value. Wrap this inside container.
        Also we are slicing the list skipping the first item in list.
    {% endcomment %}
    <div class="main-content">
        <div class="articles">
            <h2><i class="fa-solid fa-square"></i>latest</h2>
        {% for post in post_list|slice:'1:' %}
            <article class="post">
                <div class="post-image">
                    <a href="{% url 'main:post-detail' post.slug %}"><img src="{{post.image.url}}" alt="" class="m-img"></a>
                </div>
                <div class="post-dt">
                    <a class="c-link" href="{% url 'main:category' post.category %}">{{post.category}}</a>
                    <h3 class="p-title"><a href="{% url 'main:post-detail' post.slug %}">{{post.title}}</a></h3>
                    <p class="p-snippet">{{post.snippets}}</p>
                    <div class="m-post-meta">
                        <a class="post-author" href="{% url 'accounts:profile' post.author %}">
                        {% if post.author.user_image %}
                        <img src="{{post.author.user_image.url}}" class="post-ai">
                        {% else %}
                        <img src="{% static 'images/default.png' %}" class="post-ai">
                        {% endif %}
                        {{post.author.first_name}} {{post.author.last_name}}</a>
                        <p class="time">{{post.pub_date|naturaltime}}</p>
                    </div>
                </div>
            </article>
            <hr class="m-border-line">
        {% endfor %}
        </div>
        <div class="sidebar"></div>
    </div>
</div>
{% endblock %}

main/templates/main/post.html
{% extends 'main/base.html' %}
{% load static %}

{% block title%}
{{ post.title }} | Social Blogging
{% endblock %}

{%block start%}
<div class="w-content">
    <article class="w-article article">
        <header class="article-heading">
            <span>
                <a href="#" class="w-category">{{ post.category }}</a>
            </span>
            <h1 class="heading-title">{{ post.title }}</h1>
            <p class="heading-snippet">{{ post.snippets }}</p>
            <div class="heading-meta">
                <span class="w-author-by">by</span><a href="{% url 'accounts:profile' post.author %}" class="w-author">
                    {{ post.author.first_name }} {{post.author.last_name}}</a>
                <span class="meta-p-date"><i class="fa-solid fa-file-lines"></i>Posted {{ post.pub_date|date }}</span>
            </div>
            <div class="heading-image">
                <img class="header-image" src="{{ post.image.url }}" alt="">
            </div>
        </header>
        <section class="article-body" id="article-body">
            {{post.body|safe}}
        </section>
        <footer class="article-footer">
            <div class="author-bio">
                <div class="author-bio-heading">About The Author</div>
                {% if post.author.user_image %}
                <img class="author-bio-img" src="{{post.author.user_image.url}}">
                {% else %}
                <img class="author-bio-img" src="{% static 'images/default.png' %}">
                {% endif %}
                <div class="author-bio-info">
                    <a href="{% url 'accounts:profile' post.author %}" class="author-1">{{post.author.first_name}} {{post.author.last_name}}</a>
                    <p class="author-about">{{post.author.about}}</p>
                </div>
            </div>
        </footer>
    </article>
</div>
{% endblock %}

main/templates/main/profile.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/profile.css' %}">
{% endblock %}

{% block title%}
{{ members.username }}'s Profile
{% endblock %}

{% block start %}
<div class="p-container">
    <div class="p-wrapper">
        <div class="p-width">
            <div class="img">
                {% if members.user_image %}
                <img src="{{members.user_image.url}}" alt="" class="user-img">
                {% else %}
                <img src="{% static 'images/default.png' %}" class="user-img">
                {% endif %}
            </div>
            <div class="author-sec">
                <p>{{ members.first_name }} {{members.last_name}}</p>
                <span class="abt">{{ members.about }}</span>
                <span class="post-no">articles published: {{user_post|length}}</span>
            </div>
        </div>
    </div>
    <div class="profile_post">
        <div class="p-articles">
            {% for post in user_post %}
            <article class="post">
                <div class="post-image">
                    <a href="{% url 'main:post-detail' post.slug %}"><img src="{{post.image.url}}" alt="" class="m-img"></a>
                </div>
                <div class="post-dt">
                    <a class="c-link" href="{% url 'main:category' post.category %}">{{post.category}}</a>
                    <h3 class="p-title"><a href="{% url 'main:post-detail' post.slug %}">{{post.title}}</a></h3>
                    <p class="p-snippet">{{post.snippets}}</p>
                    <div class="m-post-meta">
                        <p class="time">Published {{post.pub_date|naturaltime}}</p>
                    </div>
                </div>
            </article>
            <hr class="m-border-line">
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/search.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Search{% endblock %}

{% block start %}
<div class="search-sec">
    <div class="main-content">
        <div class="articles">
            <h2 class="s-title"><i class="fa-solid fa-square"></i>We found {{object_list|length}} result matching Your search</h2>
            {% for post in object_list %}
            <article class="post">
                <div class="post-image">
                    <a href="{% url 'main:post-detail' post.slug %}"><img src="{{post.image.url}}" alt=""
                            class="m-img"></a>
                </div>
                <div class="post-dt">
                    <a class="c-link" href="#">{{post.category}}</a>
                    <h3 class="p-title"><a href="{% url 'main:post-detail' post.slug %}">{{post.title}}</a></h3>
                    <p class="p-snippet">{{post.snippets}}</p>
                    <div class="m-post-meta">
                        <a class="post-author" href="{% url 'accounts:profile' post.author %}">
                            {% if post.author.user_image %}
                            <img src="{{post.author.user_image.url}}" class="post-ai">
                            {% else %}
                            <img src="{% static 'images/default.png' %}" class="post-ai">
                            {% endif %}
                            {{post.author.first_name}} {{post.author.last_name}}</a>
                        <p class="time">{{post.pub_date|naturaltime}}</p>
                    </div>
                </div>
            </article>
            <hr class="m-border-line">
            {% empty %}
            <p class="nf">NO SEARCH RESULTS FOUND!</p>
            {% endfor %}
        </div>
        <div class="sidebar">Sidebar for ads</div>
    </div>
</div>
{% endblock %}

main/templates/main/your_post.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}

{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/my_post.css' %}">
{% endblock %}

{% block title %}My Post | Social blogging{% endblock %}

{% block start %}
<div class="container-u1">
    <div class="u-articles">
        <h2><i class="fa-solid fa-square"></i>Your Post</h2>
        {% for post in post_list %}
        <article class="u-posts">
            <div class="post-image">
                <a href="{% url 'main:post-detail' post.slug %}"><img src="{{post.image.url}}" alt="" class="m-img"></a>
            </div>
            <div class="post-dt">
                <a class="c-link" href="#">{{post.category}}</a>
                <h3 class="p-title"><a href="{% url 'main:post-detail' post.slug %}">{{post.title}}</a></h3>
                <p class="p-snippet">{{post.snippets}}</p>
                <div class="m-post-meta">
                    <a class="post-author" href="{% url 'accounts:profile' post.author %}">
                        {% if post.author.user_image %}
                        <img src="{{post.author.user_image.url}}" class="post-ai">
                        {% else %}
                        <img src="{% static 'images/default.png' %}" class="post-ai">
                        {% endif %}
                        {{post.author.first_name}} {{post.author.last_name}}</a>
                    <p class="time">{{post.pub_date|naturaltime}}</p>
                </div>
            </div>
            <div class="edit-author">
                <a class='btn btn-primary' style="margin-left: 30px" href="{% url 'main:edit-post' post.slug %}">Edit</a>
                <a class='btn btn-danger' style="margin-left: 30px" href="{% url 'main:delete-post' post.slug %}">Delete</a>
            </div>
        </article>
        <hr class="m-border-line">
        {% endfor %}
    </div>
</div>
{% endblock %}



<!-- <a style="margin-left: 30px" href="{% url 'main:edit-post' post.slug %}">Edit</a>
<a style="margin-left: 30px" href="{% url 'main:delete-post' post.slug %}">Delete</a> -->